on:
  push:
  schedule:
    # JST で毎週土曜 12:00 (UTC で毎週土曜 3:00) に実行
    - cron: '0 3 * * SAT'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: microsoft/playwright-github-action@v1

      - uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-e2e-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-e2e-

      - name: yarn install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: yarn run test:e2e-test
        run: yarn run test:e2e-test
