on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-nodejs-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.OS }}-nodejs-

      - name: yarn install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: yarn run lint
        run: yarn run lint

      - name: yarn run build
        run: yarn run build

      - name: yarn run test:unit-test
        run: yarn run test:unit-test
